### ISSUE TITLE
Memory leak during during the font creation/destruction process.

### ISSUE THREAD

**Issue by 333fps** [dwjclark11/Scion2D#8]
**Description**
Memory leak during during the font creation/destruction process.
* Heap allocation occurs in FontLoader.cpp(33): "auto data = (void*)new stbtt_bakedchar[ 96 ]:"
* And freed in  Font.cpp(22): "delete m_pData;""

Here only 8 bytes (on 64bit machine) will be deallocated because the class does'nt know the size of 96\*sizeof(stbtt_bakedchar) but only sizeof(void*) and misses the complete type.

**Possible mitigation**
* Pass the array as a smart pointer<stbtt_bakedchar>, after all, the FontLoader.cpp and the Font.cpp class both include <SOIL/stb_truetype.h>
* Pass the array as stbtt_bakedchar** and use a C-style deallocator after use (conflicts with the principle of a resource manager)
* Make the Font class responsible of aquisition and destruction (RAII) and make it stick with the glGenTextures/glDeleteTextures
* Pass the data by value using intermediate object of known type/size (possibly hidden from public API)
* Pass the data using std_shared_ptr with custom deleter
* Use pimpl where the public headers uses void* but the implementation knows the complete type

etc :)

**Comment by dwjclark11** [comment]
@333fps Great catch!

**Comment by dwjclark11** [comment]
@333fps Good afternoon, I have been looking into this and I believe that the changes here 8-memory-leak-during-during-the-font-creationdestruction-process should cover this issue.

**Comment by 333fps** [comment]
I Dustin, i think this even eve simpler :
https://github.com/333fps/Scion2D/commit/715d921d5038f9eb90947f29dd9260f055b00e0c, as only 96 chars are used by the library:
![image](https://github.com/user-attachments/assets/cf09bf72-c96a-4448-ab80-ea5a9fba6942)

**Comment by dwjclark11** [comment]
@333fps Nice, that is way simpler. We can then just keep the void pointer an convert in the dtor. Great stuff. If you make the PR, I will merge it in. I am going to close the new branch I created today. Thanks.

**Comment by dwjclark11** [comment]
@333fps Actually, I already have it open. I can make the change. Thanks a lot.

**Comment by dwjclark11** [comment]
Fix has been merged 0931ef3 Thanks.
